modLoader = "lowcodefml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL = "https://github.com/OptimisticDeving/decent-discord-bridge/issues"

[[mods]]
modId = "decent_discord_bridge"
version = "${version}"
displayName = "Decent Discord Bridge"
description = "An attempt at writing a decent Discord bridge for the Fabric ecosystem."
authors = "OptimisticDev"
modUrl = "https://github.com/OptimisticDeving/decent-discord-bridge/"
displayURL = "https://github.com/OptimisticDeving/decent-discord-bridge/"
displayTest = "NONE"

features = { java_version = "[21,)" }

[[dependencies.decent_discord_bridge]]
modId = "minecraft"
versionRange = "1.20.1"
mandatory = true

[[dependencies.decent_discord_bridge]]
modId = "kotlinforforge"
versionRange = "[4.12.0,)"
mandatory = true
ordering = "AFTER"
